In [1]:
import numpy as np

#creating arrays

a = np.array([1, 2, 3, 4, 5]) 
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]]) 
print(b)

c=np.zeros((3,4))
print(c)

d = np.ones((2, 2)) 
print(d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [3]:
#Performing mathematical operations on numpy arrays

#Additionn

a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [4]:
#Multiplication

d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
f=d*e
print(f)

[[ 5 12]
 [21 32]]


In [6]:
#Performing matrix multiplication

g=np.array([[1,2],[3,4]])
h=np.array([[5,6],[7,8]])
i=np.dot(g,h)
print(i)


[[19 22]
 [43 50]]
